name: Update Docker Image on Upstream Tag Change

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add upstream repository
        run: git remote add upstream https://github.com/krille-chan/fluffychat.git

      - name: Fetch tags from upstream
        run: git fetch upstream --tags

      - name: Get the latest tag
        id: get_latest_tag
        run: echo "latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Print the latest tag
        run: echo "Latest tag is: ${{ env.latest_tag }}"

      - name: Check out the latest tag
        run: git checkout tags/${{ env.latest_tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fluffychat:${{ env.latest_tag }}

      - name: Clean up unused Docker resources
        run: docker system prune -f
